const actionTypes = {
  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER',
  SHOW_AUTH_DIALOG: 'SHOW_AUTH_DIALOG',
  FETCH_CART: 'FETCH_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
}

export default actionTypes
