const actionTypes = {
  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER',
  SHOW_AUTH_DIALOG: 'SHOW_AUTH_DIALOG',
  INIT_CART: 'INIT_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  UPDATE_CART_INFO: 'UPDATE_CART_INFO',
}

export default actionTypes
